[package]
name = "game_of_life"
version = "0.1.0"
authors = ["ndts55 <nicolastorres@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.0"
